### PR TITLE
Send output through system keyboard to enable voice typing in any application

### PR DESCRIPTION
**Pull request by jnnnnn**
I thought this was a really useful feature, and it only takes a couple of lines of code.

Using the existing streaming example, you can now "type" by speaking in any application on your computer.

### CODE REVIEW

**Comment by irab** [comment]
Would be good to update the Readme too as well if this gets added.

**Review by lissyx — APPROVED** [review]
LGTM but please document that in the readme!

**Comment by lissyx** [comment]
@jnnnnn Also, would be nice to have the same PR on `r0.8` as well

**Comment by jnnnnn** [comment]
I have updated the readme and cherry-picked the two commits into #89 on the 0.8 branch.

Thanks, this is a really useful project!

**Review by lissyx — APPROVED** [review]

**Pull request merged**
