### PR TITLE
New example: Universal Windows Platform with Audio Graph API

### PR DESCRIPTION
**Pull request by erksch**
Hey there!

I really wanted to use DeepSpeech on Universal Windows Platform, but sadly the only example available for windows was the WPF example. Since most of the libraries used there, are not really usable for UWP (NAudio and CSCore are not compatible as far as I know), I decided to dive into it and create a working version for UWP.

For audio processing I am using the [UWP Audio Graph API](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/audio-graphs) which seems to be the only option to me where you can easily convert to 16000Hz, 16bit mono (or any format you like). I also tested out MediaCapture but couldn't figure out how to subsample easily. 

~The Audio Graph API is pretty neat but has one big flaw: Although it reads file or microphone input correctly at 16000Hz, 16bit mono it weirdly only returns individual samples as floats instead of shorts. But the floats are not two shorts concatenated, they are weirdly mapped to every possible short (`0 0 - 255 255`). I asked about that on stackoverflow in [this question](https://stackoverflow.com/questions/61507432/uwp-audiograph-api-frameoutputnode-read-bytes-wrong) if you want to read more about it. But I managed to map the floats correctly to their corresponding shorts in the `convertFloatToShort` method. The methods seems random but it reverses the weird float -> short mapping and is 100% correct.~

Regarding the general code I am not an expert in C# or UWP programming, so if there are any code style flaws feel free to correct me.

I hope it's a useful contribution.

(Thanks to @MarcelSchmidberger for helping with this code a lot.)

Before you can use the app, you have to copy the `.pbmm` and `.scorer` files to the `models` dir, include them in the project in Visual Studio and set their `Build Action` to `Content` and `Copy to Output Directory` to `Copy if newer`. If a .NET expert knows a better way to copy model files to the project please let me know. 

I will provide a README as soon as possible.

Annotation 2020-04-30 220124

### CODE REVIEW

**Comment by reuben** [comment]
I'm impressed you were able to reconstruct the two bytes of a short from the float value like that, but are you sure you're not overcomplicating a simple scale conversion? See for example http://blog.bjornroche.com/2009/12/int-float-int-its-jungle-out-there.html or https://stackoverflow.com/a/15094612/346048

**Comment by erksch** [comment]
Man this would have saved me hours 😅 I guess my googling skills are not fully fleshed out yet. I'll update the code tomorrow.

**Comment by lissyx** [comment]
Did we forgot to merge that ? @reuben @erksch

**Comment by reuben** [comment]
I did!

**Comment by AbeerAhmedKhawaja** [comment]
Sorry i am new to DeepSpeech. I am running into a problem, when compiling the VS is unable to find DeepSpeechClient. 

How can i solve this? 

image

**Comment by lissyx** [comment]
> Sorry i am new to DeepSpeech. I am running into a problem, when compiling the VS is unable to find DeepSpeechClient.
> 
> How can i solve this?
> 
> image

Please reach for support on Discourse

**Comment by erksch** [comment]
Looks like the problem we are currently tackling in [this issue](https://github.com/mozilla/DeepSpeech/issues/2937). There is also a workaround for your problem @AbeerAhmedKhawaja.

**Pull request merged**
