### PR TITLE
New example - AutoSub

### PR DESCRIPTION
**Pull request by abhirooptalasila**
Hi
I worked on [AutoSub](https://github.com/abhirooptalasila/AutoSub) a couple of months ago. Just came across this repo and thought of contributing. 
Cheers

### CODE REVIEW

**Comment by lissyx** [comment]
Before we review can you open the same pr on master branch as well ? Thanks

**Comment by abhirooptalasila** [comment]
> Before we review can you open the same pr on master branch as well ? Thanks

Updated PR base to master.

**Comment by lissyx** [comment]
> > Before we review can you open the same pr on master branch as well ? Thanks
> 
> Updated PR base to master.

You got me wrong, doing against `r0.9` was fine, we'd just need à second one 😇

**Comment by abhirooptalasila** [comment]
I think I made a mess. Will open new PRs to both branches. Sorry!

**Pull request closed without merging**
