### PR TITLE
Add AutoSub to master

### PR DESCRIPTION
**Pull request by abhirooptalasila**
As suggested.
@lissyx please review.

### CODE REVIEW

**Review by lissyx — APPROVED** [review]

**Comment by lissyx** [comment]
@abhirooptalasila It'd be awesome if you can add GitHub Actions test coverage for that on https://github.com/mozilla/DeepSpeech

**Comment by abhirooptalasila** [comment]
Thank you!
Can you also update [README.rst](https://github.com/mozilla/DeepSpeech-examples/blob/r0.9/README.rst) to include AutoSub under Python subheading?

**Comment by abhirooptalasila** [comment]
> 
> 
> @abhirooptalasila It'd be awesome if you can add GitHub Actions test coverage for that on https://github.com/mozilla/DeepSpeech

I didn't get that. Can you elaborate?

**Comment by lissyx** [comment]
> Thank you!
> Can you also update [README.rst](https://github.com/mozilla/DeepSpeech-examples/blob/r0.9/README.rst) to include AutoSub under Python subheading?

Please PR it

**Comment by lissyx** [comment]
> > @abhirooptalasila It'd be awesome if you can add GitHub Actions test coverage for that on https://github.com/mozilla/DeepSpeech
> 
> I didn't get that. Can you elaborate?

We had testing on TaskCluster for some examples, e.g., https://github.com/mozilla/DeepSpeech/blob/master/taskcluster/examples-vad_transcriber-py35.yml but we have now moved to GitHub Actions, we could use help and feedback as well as PR to implement examples testing back.

https://github.com/mozilla/DeepSpeech/projects/13
https://github.com/mozilla/DeepSpeech/issues/3317

**Comment by abhirooptalasila** [comment]
> 
> 
> > Thank you!
> > Can you also update [README.rst](https://github.com/mozilla/DeepSpeech-examples/blob/r0.9/README.rst) to include AutoSub under Python subheading?
> 
> Please PR it

#130 and #131

**Comment by abhirooptalasila** [comment]
> 
> 
> > > @abhirooptalasila It'd be awesome if you can add GitHub Actions test coverage for that on https://github.com/mozilla/DeepSpeech
> > 
> > 
> > I didn't get that. Can you elaborate?
> 
> We had testing on TaskCluster for some examples, e.g., https://github.com/mozilla/DeepSpeech/blob/master/taskcluster/examples-vad_transcriber-py35.yml but we have now moved to GitHub Actions, we could use help and feedback as well as PR to implement examples testing back.
> 
> https://github.com/mozilla/DeepSpeech/projects/13
> [mozilla/DeepSpeech#3317](https://github.com/mozilla/DeepSpeech/issues/3317)

I haven't worked with GitHub Actions yet, but I'll have a look at update you soon 👍

**Pull request merged**
